// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence_Layer.Data;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200916164709_Initial_db_change")]
    partial class Initial_db_change
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Persistence.Models.Control", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountNoLength");

                    b.Property<int>("BusinessId");

                    b.Property<DateTime>("CurrentDate");

                    b.Property<string>("ReportFolderName");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("Controls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountNoLength = 20,
                            BusinessId = 1,
                            CurrentDate = new DateTime(2020, 9, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            ReportFolderName = "Reports\\"
                        });
                });

            modelBuilder.Entity("Persistence.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Blob");

                    b.Property<string>("Comment");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("ImageType")
                        .HasMaxLength(50);

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsVisible");

                    b.Property<int>("LastModifiedBy");

                    b.Property<DateTime?>("LastModifiedDate");

                    b.Property<int>("ReferenceId");

                    b.Property<string>("ReferneceType")
                        .IsRequired()
                        .HasMaxLength(1);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("Size");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Persistence.Models.TransactionCode", b =>
                {
                    b.Property<int>("TranCode");

                    b.Property<string>("Description")
                        .HasMaxLength(50);

                    b.Property<bool>("IsDebit");

                    b.HasKey("TranCode");

                    b.ToTable("TransactionCodes");

                    b.HasData(
                        new
                        {
                            TranCode = 100,
                            Description = "Credit Tran Code",
                            IsDebit = false
                        },
                        new
                        {
                            TranCode = 200,
                            Description = "Debit Tran Code",
                            IsDebit = true
                        });
                });

            modelBuilder.Entity("Persistence.Models.TransactionTypeDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsVisible");

                    b.Property<int>("LastModifiedBy");

                    b.Property<DateTime?>("LastModifiedDate");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("TranCode");

                    b.Property<int>("TransactionTypeId");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("TranCode");

                    b.HasIndex("TransactionTypeId");

                    b.ToTable("TransactionTypeDetails");
                });

            modelBuilder.Entity("Persistence_Layer.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountNo")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("AccountTypeId");

                    b.Property<string>("Address1")
                        .HasMaxLength(100);

                    b.Property<string>("Address2")
                        .HasMaxLength(100);

                    b.Property<decimal>("Balance");

                    b.Property<int>("ClientId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("Description");

                    b.Property<string>("Email")
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsMain");

                    b.Property<bool>("IsVisible");

                    b.Property<int>("LastModifiedBy");

                    b.Property<DateTime?>("LastModifiedDate");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50);

                    b.Property<string>("Note");

                    b.Property<string>("Phone")
                        .HasMaxLength(12);

                    b.Property<int?>("RelationshipId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("SortId");

                    b.Property<string>("State")
                        .HasMaxLength(2);

                    b.Property<string>("ZipCode")
                        .HasMaxLength(5);

                    b.HasKey("Id");

                    b.HasIndex("AccountTypeId");

                    b.HasIndex("ClientId");

                    b.HasIndex("RelationshipId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Persistence_Layer.Models.AccountHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountNo");

                    b.Property<int>("AccountTypeId");

                    b.Property<string>("Address1")
                        .HasMaxLength(100);

                    b.Property<string>("Address2")
                        .HasMaxLength(100);

                    b.Property<decimal>("Balance");

                    b.Property<int>("ClientId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("DateAdded");

                    b.Property<string>("Description");

                    b.Property<string>("Email")
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsMain");

                    b.Property<bool>("IsVisible");

                    b.Property<int>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50);

                    b.Property<string>("Note");

                    b.Property<string>("Phone")
                        .HasMaxLength(12);

                    b.Property<int?>("RelationshipId");

                    b.Property<byte[]>("RowVersion");

                    b.Property<int>("SortId");

                    b.Property<string>("State")
                        .HasMaxLength(2);

                    b.Property<string>("ZipCode")
                        .HasMaxLength(5);

                    b.HasKey("Id");

                    b.HasIndex("AccountTypeId");

                    b.HasIndex("ClientId");

                    b.HasIndex("RelationshipId");

                    b.ToTable("AccountHistories");
                });

            modelBuilder.Entity("Persistence_Layer.Models.AccountType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("Description")
                        .HasMaxLength(100);

                    b.Property<int>("GroupId");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsVisible");

                    b.Property<int>("LastModifiedBy");

                    b.Property<DateTime?>("LastModifiedDate");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("ShortName")
                        .HasMaxLength(40);

                    b.Property<int>("SortId");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("AccountTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            Description = "Normal Account",
                            GroupId = 1,
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0,
                            ShortName = "NA",
                            SortId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            Description = "Cash Account",
                            GroupId = 2,
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0,
                            ShortName = "CA",
                            SortId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            Description = "Bank Account",
                            GroupId = 2,
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0,
                            ShortName = "BA",
                            SortId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            Description = "Income Account",
                            GroupId = 2,
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0,
                            ShortName = "IA",
                            SortId = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            Description = "Expense Account",
                            GroupId = 2,
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0,
                            ShortName = "EA",
                            SortId = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            Description = "Payable Account",
                            GroupId = 2,
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0,
                            ShortName = "PA",
                            SortId = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            Description = "Receivable Account",
                            GroupId = 2,
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0,
                            ShortName = "RA",
                            SortId = 7
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            Description = "Assets Account",
                            GroupId = 2,
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0,
                            ShortName = "AA",
                            SortId = 8
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            Description = "Liabilities Account",
                            GroupId = 2,
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0,
                            ShortName = "LA",
                            SortId = 9
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            Description = "Other Account",
                            GroupId = 3,
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0,
                            ShortName = "OA",
                            SortId = 10
                        });
                });

            modelBuilder.Entity("Persistence_Layer.Models.Business", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address1")
                        .HasMaxLength(255);

                    b.Property<string>("Address2")
                        .HasMaxLength(255);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("Description")
                        .HasMaxLength(255);

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsVisible");

                    b.Property<int>("LastModifiedBy");

                    b.Property<DateTime?>("LastModifiedDate");

                    b.Property<string>("Name")
                        .HasMaxLength(255);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("State")
                        .HasMaxLength(2);

                    b.Property<string>("ZipCode")
                        .HasMaxLength(5);

                    b.HasKey("Id");

                    b.ToTable("Businesses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address1 = "Address 1",
                            Address2 = "Address 2",
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0,
                            Name = "Your Business Name",
                            State = "zz",
                            ZipCode = "zzzzz"
                        });
                });

            modelBuilder.Entity("Persistence_Layer.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BusinessId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsVisible");

                    b.Property<int>("LastModifiedBy");

                    b.Property<DateTime?>("LastModifiedDate");

                    b.Property<string>("Name")
                        .HasMaxLength(200);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusinessId = 1,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0,
                            Name = "Internal Client"
                        },
                        new
                        {
                            Id = 2,
                            BusinessId = 1,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0,
                            Name = "Default Client"
                        });
                });

            modelBuilder.Entity("Persistence_Layer.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsVisible");

                    b.Property<int>("LastModifiedBy");

                    b.Property<DateTime?>("LastModifiedDate");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("SortId");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            Description = "External Group",
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0,
                            SortId = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            Description = "Internal Group",
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0,
                            SortId = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            Description = "Other Group",
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0,
                            SortId = 0
                        });
                });

            modelBuilder.Entity("Persistence_Layer.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("IconName")
                        .HasMaxLength(100);

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsVisible");

                    b.Property<int>("LastModifiedBy");

                    b.Property<DateTime?>("LastModifiedDate");

                    b.Property<string>("Link");

                    b.Property<int>("MainMenuId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("SortId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("UserRoles")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0,
                            Link = "home",
                            MainMenuId = 0,
                            SortId = 1,
                            Title = "Home",
                            UserRoles = "1,2,3"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0,
                            Link = "account",
                            MainMenuId = 0,
                            SortId = 2,
                            Title = "Account",
                            UserRoles = "1,2,3"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0,
                            Link = "transaction",
                            MainMenuId = 0,
                            SortId = 3,
                            Title = "Transaction",
                            UserRoles = "1,2,3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0,
                            Link = "report",
                            MainMenuId = 0,
                            SortId = 4,
                            Title = "Reports",
                            UserRoles = "1,2,3"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0,
                            Link = "code",
                            MainMenuId = 0,
                            SortId = 5,
                            Title = "Code System",
                            UserRoles = "1"
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0,
                            Link = "setting",
                            MainMenuId = 0,
                            SortId = 6,
                            Title = "Setting",
                            UserRoles = "1"
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0,
                            Link = "tool",
                            MainMenuId = 0,
                            SortId = 7,
                            Title = "Tools",
                            UserRoles = "1"
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0,
                            Link = "menu",
                            MainMenuId = 5,
                            SortId = 1,
                            Title = "Menu",
                            UserRoles = "1"
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0,
                            Link = "role",
                            MainMenuId = 6,
                            SortId = 1,
                            Title = "Role",
                            UserRoles = "1"
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0,
                            Link = "user",
                            MainMenuId = 6,
                            SortId = 2,
                            Title = "User",
                            UserRoles = "1"
                        });
                });

            modelBuilder.Entity("Persistence_Layer.Models.Relationship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsVisible");

                    b.Property<int>("LastModifiedBy");

                    b.Property<DateTime?>("LastModifiedDate");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.ToTable("Relationships");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            Description = "~",
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            Description = "Mother",
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            Description = "Parent",
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            Description = "Son",
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            Description = "Daughter",
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            Description = "Husband",
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            Description = "Wife",
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            Description = "Spouse",
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            Description = "Brother",
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            Description = "Sister",
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            Description = "Sibling",
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            Description = "Elder brother/sister",
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0
                        },
                        new
                        {
                            Id = 13,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            Description = "Younger brother/sister",
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0
                        },
                        new
                        {
                            Id = 14,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            Description = "Grandfather",
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0
                        },
                        new
                        {
                            Id = 15,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            Description = "Grandmother",
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0
                        },
                        new
                        {
                            Id = 16,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            Description = "Father",
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0
                        },
                        new
                        {
                            Id = 17,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 10, DateTimeKind.Local).AddTicks(2308),
                            Description = "Other",
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0
                        });
                });

            modelBuilder.Entity("Persistence_Layer.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("Description")
                        .HasMaxLength(50);

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsVisible");

                    b.Property<int>("LastModifiedBy");

                    b.Property<DateTime?>("LastModifiedDate");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 5, DateTimeKind.Local).AddTicks(2141),
                            Description = "Admin",
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 9, DateTimeKind.Local).AddTicks(2148),
                            Description = "User",
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(2020, 9, 16, 12, 47, 9, 9, DateTimeKind.Local).AddTicks(2148),
                            Description = "Viewer",
                            IsActive = true,
                            IsVisible = true,
                            LastModifiedBy = 0
                        });
                });

            modelBuilder.Entity("Persistence_Layer.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountId");

                    b.Property<decimal>("Amount");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("Description1")
                        .HasMaxLength(200);

                    b.Property<string>("Description2")
                        .HasMaxLength(400);

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsVisible");

                    b.Property<int>("LastModifiedBy");

                    b.Property<DateTime?>("LastModifiedDate");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("TranId")
                        .HasMaxLength(20);

                    b.Property<DateTime>("TransactionDate");

                    b.Property<int>("TransactionTypeId");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("TransactionTypeId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Persistence_Layer.Models.TransactionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("Description")
                        .HasMaxLength(100);

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsVisible");

                    b.Property<int>("LastModifiedBy");

                    b.Property<DateTime?>("LastModifiedDate");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("SortId");

                    b.HasKey("Id");

                    b.ToTable("TransactionTypes");
                });

            modelBuilder.Entity("Persistence_Layer.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("Email")
                        .HasMaxLength(100);

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsVisible");

                    b.Property<int>("LastModifiedBy");

                    b.Property<DateTime?>("LastModifiedDate");

                    b.Property<DateTime>("LastPasswordChangedOn");

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.Property<int>("PasswordChangedCount");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Phone")
                        .HasMaxLength(20);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("UserName")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Persistence_Layer.Models.UserActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActionName");

                    b.Property<string>("Comment");

                    b.Property<string>("ControllerName");

                    b.Property<DateTime>("DateRequested");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.ToTable("UserActivities");
                });

            modelBuilder.Entity("Persistence_Layer.Models.UserHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Email");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsVisible");

                    b.Property<int>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<DateTime>("LastPasswordChangedOn");

                    b.Property<string>("Name");

                    b.Property<int>("PasswordChangedCount");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Phone");

                    b.Property<byte[]>("RowVersion");

                    b.Property<string>("UserRole");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("UserHistories");
                });

            modelBuilder.Entity("Persistence_Layer.Models.UserRole", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("Persistence.Models.Control", b =>
                {
                    b.HasOne("Persistence_Layer.Models.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Persistence.Models.TransactionTypeDetail", b =>
                {
                    b.HasOne("Persistence_Layer.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Persistence.Models.TransactionCode", "TransactionCode")
                        .WithMany()
                        .HasForeignKey("TranCode")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Persistence_Layer.Models.TransactionType", "TransactionType")
                        .WithMany()
                        .HasForeignKey("TransactionTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Persistence_Layer.Models.Account", b =>
                {
                    b.HasOne("Persistence_Layer.Models.AccountType", "AccountType")
                        .WithMany()
                        .HasForeignKey("AccountTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Persistence_Layer.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Persistence_Layer.Models.Relationship", "Relationship")
                        .WithMany()
                        .HasForeignKey("RelationshipId");
                });

            modelBuilder.Entity("Persistence_Layer.Models.AccountHistory", b =>
                {
                    b.HasOne("Persistence_Layer.Models.AccountType", "AccountType")
                        .WithMany()
                        .HasForeignKey("AccountTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Persistence_Layer.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Persistence_Layer.Models.Relationship", "Relationship")
                        .WithMany()
                        .HasForeignKey("RelationshipId");
                });

            modelBuilder.Entity("Persistence_Layer.Models.AccountType", b =>
                {
                    b.HasOne("Persistence_Layer.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Persistence_Layer.Models.Client", b =>
                {
                    b.HasOne("Persistence_Layer.Models.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Persistence_Layer.Models.Transaction", b =>
                {
                    b.HasOne("Persistence_Layer.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Persistence_Layer.Models.TransactionType", "TransactionType")
                        .WithMany()
                        .HasForeignKey("TransactionTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Persistence_Layer.Models.UserRole", b =>
                {
                    b.HasOne("Persistence_Layer.Models.Role", "Role")
                        .WithMany("UserRole")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Persistence_Layer.Models.User", "User")
                        .WithMany("UserRole")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
